sample_rate: 16000
log_prediction: true
load_weights_from_checkpoint: null
ctc_reduction: mean_batch
train_ds:
  manifest_filepath: /data/librispeech_withsp2/manifests/librispeech_train_withSP.json
  sample_rate: 16000
  batch_size: 128
  shuffle: true
  num_workers: 8
  pin_memory: true
  use_start_end_token: false
  trim_silence: false
  max_duration: 16.7
  min_duration: 0.1
  shuffle_n: 2048
  is_tarred: false
  tarred_audio_filepaths: /data/asr_set_1.4/train_no_appen/train_no_appen__OP_0..1023_CL_.tar
validation_ds:
  manifest_filepath: []  # Configure with your validation datasets
  sample_rate: 16000
  batch_size: 64
  shuffle: false
  num_workers: 8
  pin_memory: true
  use_start_end_token: false
  is_tarred: false
  tarred_audio_filepaths: ""  # Configure with your evaluation datasets
test_ds:
  manifest_filepath: []  # Configure with your test datasets
  sample_rate: 16000
  batch_size: 64
  shuffle: false
  num_workers: 8
  pin_memory: true
  use_start_end_token: false
  is_tarred: false
  tarred_audio_filepaths: ""  # Configure with your evaluation datasets
tokenizer:
  dir: /tokenizers/librispeech/librispeech_tokenizer_wpe_v128/
  type: wpe
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  sample_rate: 16000
  normalize: per_feature
  window_size: 0.025
  window_stride: 0.01
  window: hann
  features: 80
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  pad_to: 0
  stft_conv: false
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 5
  freq_width: 27
  time_width: 0.05
encoder:
  _target_: nemo.collections.asr.modules.ConformerEncoder
  feat_in: 80
  feat_out: -1
  n_layers: 16
  d_model: 176
  subsampling: striding
  subsampling_factor: 4
  subsampling_conv_channels: 176
  ff_expansion_factor: 4
  self_attention_model: rel_pos
  n_heads: 4
  xscaling: true
  untie_biases: true
  pos_emb_max_len: 5000
  conv_kernel_size: 31
  dropout: 0.1
  dropout_emb: 0.0
  dropout_att: 0.1
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoder
  feat_in: 176
  num_classes: 128
  vocabulary:
  - '[PAD]'
  - '[UNK]'
  - '[CLS]'
  - '[SEP]'
  - '[MASK]'
  - ''''
  - a
  - b
  - c
  - d
  - e
  - f
  - g
  - h
  - i
  - j
  - k
  - l
  - m
  - 'n'
  - o
  - p
  - q
  - r
  - s
  - t
  - u
  - v
  - w
  - x
  - 'y'
  - z
  - '##r'
  - '##a'
  - '##y'
  - '##f'
  - '##i'
  - '##s'
  - '##h'
  - '##d'
  - '##e'
  - '##p'
  - '##o'
  - '##l'
  - '##c'
  - '##n'
  - '##m'
  - '##t'
  - '##g'
  - '##w'
  - '##v'
  - '##u'
  - '##x'
  - '##b'
  - '##k'
  - '##z'
  - '##q'
  - '##j'
  - th
  - the
  - '##er'
  - '##nd'
  - '##in'
  - '##ed'
  - '##ou'
  - '##at'
  - '##en'
  - and
  - '##or'
  - '##es'
  - to
  - of
  - '##on'
  - '##is'
  - '##ing'
  - '##ar'
  - '##it'
  - '##as'
  - '##an'
  - '##ll'
  - in
  - '##re'
  - wh
  - he
  - '##om'
  - be
  - ha
  - '##le'
  - '##ot'
  - '##ow'
  - '##ic'
  - '##ut'
  - it
  - '##ld'
  - that
  - sh
  - '##ly'
  - was
  - '##gh'
  - '##id'
  - '##se'
  - 'on'
  - '##ve'
  - '##et'
  - '##ent'
  - you
  - '##im'
  - '##st'
  - '##ce'
  - '##ith'
  - for
  - '##ir'
  - '##ion'
  - as
  - '##ay'
  - his
  - '##al'
  - with
  - '##ur'
  - st
  - '##ter'
  - her
  - '##ver'
  - '##ch'
  - re
  - '##ad'
  - '##ght'
  - an
optim:
  name: adam
  lr: 2.0
  betas:
  - 0.9
  - 0.98
  weight_decay: 0
  sched:
    name: NoamAnnealing
    d_model: 176
    warmup_steps: 10000
    warmup_ratio: null
    min_lr: 1.0e-06
target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
